version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=clubinho
      - POSTGRES_DB=clubinho
      - POSTGRES_PASSWORD=clubinho
    networks:
      - clubinho
networks:
  clubinho:
    name: clubinho
